name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Consolidate JSON
        uses: jacklehamster/dok-compression-action@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ENV_VAR: value

      - name: Check if Consolidated JSON was created
        run: |
          if [ -f consolidated.json ]; then
            echo "Consolidated JSON file exists."
          else
            echo "Consolidated JSON file does not exist."
            exit 1
          fi
