name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Consolidate JSON
        uses: jacklehamster/dok-compression-action@v1.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ENV_VAR: value

      - name: Check if Consolidated JSON was created
        run: |
          if [ -f consolidated.json ]; then
            echo "Consolidated JSON file exists."
          else
            echo "Consolidated JSON file does not exist."
            exit 1
          fi

      - name: Commit consolidated file
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          # Add files to staging
          git add consolidated.json consolidated.dokbin

          # Check if there are changes to commit
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
            exit 0
          fi

          # Commit changes
          git commit -m "Add consolidated JSON file"
          git remote set-url origin https://github.com/${{ github.repository }}.git

      - name: Push changes # push the output folder to your repo
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: false
