name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Consolidate JSON Action
        uses: jacklehamster/dok-compression-action@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

